PLA6619 Introduction to Urban Data and Informatics I \
Tuesday, September 22, 2020 \
Week03

In [1]:
import warnings
warnings.filterwarnings("ignore")

# Lab 02
Please submit __Lab02.ipynb__ with outputs on Canvas after this lab session. 

# PART 1: Intro to Python (continued)

## 1. Range

        range()
       
This range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.

        syntax:
        range(START_NUMBER, STOP_NUMBER, STEP_NUMBER)
        

In [3]:
x = list(range(5))
print(x)

[0, 1, 2, 3, 4]


In [4]:
x = list(range(3, 6))
print(x)

[3, 4, 5]


In [5]:
x = list(range(3, 20, 2))
print(x)

[3, 5, 7, 9, 11, 13, 15, 17, 19]


## 2. Calling Functions
    min()
    max()
    sum()
    len()

In [6]:
x = list(range(15))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [7]:
print(min(x))
print(max(x))
print(sum(x))
print(len(x))

0
14
105
15


### Exercise: create a list with a sequence of number from 3 to 31, increment by 4, using range() and print mean value of the items.
* Create a list and assign variable.
* Assign variables using calling functions based on needs (e.g. min, max, sum, or len)
* Print mean value of the items in the list using mathematical expression.

In [20]:
y = list(range(3, 32, 4))
print(sum(y) / len(y))

17.0


## 3. Writing Functions
A function is a block of code with only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result. The advantage of writing functions is you can easily use funciton for repeated processes with the same parameter structure. (e.g. calculator)

    Syntax:
    
    def YOUR_FUNCTION_NAME(PARAMETERS):
        WRITE_YOUR_CODE_HERE

In [11]:
def my_function(): 
    print("Hello, world!")

In [12]:
my_function()

Hello, world!


In [13]:
def func_2(x, y):
    return x * y

In [14]:
func_2(3,6)

18

In [15]:
func_2(10, 11)

110

In [17]:
def func_3(x, y): 
    a = x + y
    b = x - y
    c = x * y
    d = x / y
    return([a,b,c,d])

func_3(3, 8)

[11, -5, 24, 0.375]

### Exercise: write a function to return average value of items in a list.

In [75]:
def average(x): 
    return sum(x) / len(x)


print(average(list(range(20))))
print(average([0,3,6,10]))

9.5
4.75


## 4. Control Statement (If-else)
* if
* elif
* else

In [21]:
a = 5
b = 10
if(b > a): 
    print("b is greater than a")

b is greater than a


In [24]:
a = 10
b = 10
if(b > a): 
    print("b is greater than a")
elif(a == b): 
    print("a equals b")

a equals b


In [25]:
a = 15
b = 10
if(b > a): 
    print("b is greater than a")
elif(a == b): 
    print("a equals b")
else: 
    print("a is greater than b")

a is greater than b


## 5. For loops
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string). This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-oriented programming languages. With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.

    Syntax:
    for item in YOUR_SEQUENCE:
        do this
        do that
        ...

In [26]:
for i in range(6): 
    print(i)

0
1
2
3
4
5


In [27]:
for city in ['New York', 'Los Angeles', 'Chicago']: 
    print("I have lived in", city)

I have lived in New York
I have lived in Los Angeles
I have lived in Chicago


In [28]:
colors = ['red', 'blue', 'yellow']
items = ['cup', 'shirt', 'pen']

for c in colors: 
    for i in items: 
        print(c, i)

red cup
red shirt
red pen
blue cup
blue shirt
blue pen
yellow cup
yellow shirt
yellow pen


In [29]:
for i in range(5): 
    if (i == 3): 
        pass
    else: 
        print(i)

0
1
2
4


In [30]:
for i in range(5): 
    if (i == 3): 
        break
    else: 
        print(i)

0
1
2


In [31]:
for i in range(5): 
    if (i == 3): 
        print("Three")
    else: 
        print(i)

0
1
2
Three
4


### Exercise: create a function to get all availabe combinations based on the following statements.
* Create two lists [1, 3, 5, 7] and [2, 4, 6, 8] using a range() function.
* Print out all available combinations of two items from each list if a multiplication result is not 12. For example, 3 and 4 shouldn't be printed out.
* Break a script once a for loop once a for loop takes 7 from the first list.
Ideal output would be 
        1 2
        1 4
        1 6
        1 8
        3 2
        3 6
        3 8
        5 2
        5 4
        5 6
        5 8

In [82]:
x = list(range(1, 8, 2))
y = list(range(2, 9, 2))

for i in x: 
    if(i == 7): 
        break
    else: 
        for j in y: 
            print(i, j)
        

1 2
1 4
1 6
1 8
3 2
3 4
3 6
3 8
5 2
5 4
5 6
5 8


# PART 2: Essential Libraries - Numpy


### Import Numpy module

In [33]:
import numpy as np

## 1. Create a numpy array

In [38]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


## 2. Shape of matrix (array)

In [40]:
x.shape

(2, 3)

## 3. Indexing

In [41]:
x[0]

array([1, 2, 3])

__Accessing array rows and columns__ 


In [44]:
x[:,0]

array([1, 4])

## 4. Numpy's arithmetic operators

In [46]:
x = np.array([1,2,3,4,5,6])

print(x+3)
print(x*3)
print(x-3)

[4 5 6 7 8 9]
[ 3  6  9 12 15 18]
[-2 -1  0  1  2  3]


In [49]:
np.log
np.exp
np.log10

AttributeError: 'numpy.ndarray' object has no attribute 'log'

## 5. Calling built-in functions

In [52]:
x = np.array([[1,2,3,4,5,6],
             [2,3,4,5,6,7],
             [3,4,5,6,7,8]])
print(x.sum())
print(x.min())
print(x.argmax())
print(x.mean())
print(x.std())

81
1
17
4.5
1.8929694486000912


In [53]:
print(np.sum(x))

81


# PART 3: Pandas


### Import pandas module


In [54]:
import pandas as pd

## 1. Create a pandas dataframe

## 2. Data shape, columns, and rows

## 3. Data types

## 4. Data indexing and selection

## 5. Sorting
    
    syntax
    YOUR_DATAFRAME.sort_values(by='COLUMN_NAME', ascending='False')   ascending='True' is default

## 6. Basic functions

# PART 4: Play with data (TIPS FOR THE ASSIGNMENT!)


## 1. Load NYC311 data (311 service requests data subset) 

In [55]:
df = pd.read_csv('../data/311_Service_Requests_01062020.csv')

In [59]:
df.head()

Unique Key            Created Date             Closed Date Agency  \
0    45321376  01/06/2020 12:00:00 AM  01/22/2020 12:00:01 AM  DOHMH   
1    45322953  01/06/2020 12:00:00 AM  01/21/2020 12:00:01 AM  DOHMH   
2    45319607  01/06/2020 12:00:00 AM  01/06/2020 12:00:01 AM  DOHMH   
3    45319110  01/06/2020 12:00:00 AM  01/21/2020 12:00:01 AM  DOHMH   
4    45319119  01/06/2020 12:00:00 AM  01/07/2020 01:35:26 PM  DOHMH   

                               Agency Name  Complaint Type Descriptor  \
0  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
1  Department of Health and Mental Hygiene  Food Poisoning  3 or More   
2  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
3  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
4  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   

                Location Type  Incident Zip                  Incident Address  \
0         1-2 Family Dwelling       10467.0            3311 WHITE PLAINS ROAD   
1  Restaurant/Bar/Deli/Bakery       11375.0                  64-18 108 STREET   
2  Restaurant/Bar/Deli/Bakery       10128.0                     1664 3 AVENUE   
3                  Restaurant       10039.0  2730 FREDRICK DOUGLASS BOULEVARD   
4         1-2 Family Dwelling       10467.0            3311 WHITE PLAINS ROAD   

   ... Vehicle Type Taxi Company Borough Taxi Pick Up Location  \
0  ...          NaN                  NaN                   NaN   
1  ...          NaN                  NaN                   NaN   
2  ...          NaN                  NaN                   NaN   
3  ...          NaN                  NaN                   NaN   
4  ...          NaN                  NaN                   NaN   

  Bridge Highway Name Bridge Highway Direction Road Ramp  \
0                 NaN                      NaN       NaN   
1                 NaN                      NaN       NaN   
2                 NaN                      NaN       NaN   
3                 NaN                      NaN       NaN   
4                 NaN                      NaN       NaN   

  Bridge Highway Segment   Latitude  Longitude  \
0                    NaN  40.873639 -73.867095   
1                    NaN  40.732517 -73.849397   
2                    NaN  40.783423 -73.950634   
3                    NaN  40.822932 -73.941832   
4                    NaN  40.873639 -73.867095   

                                   Location  
0    (40.8736393816693, -73.86709503705343)  
1   (40.73251661488513, -73.84939676972941)  
2  (40.783423466965544, -73.95063441884525)  
3   (40.82293243748226, -73.94183246541331)  
4    (40.8736393816693, -73.86709503705343)  

[5 rows x 41 columns]

In [61]:
df.tail(8)

Unique Key            Created Date             Closed Date Agency  \
6029    45336051  01/07/2020 12:00:00 AM  01/07/2020 12:00:01 AM  DOHMH   
6030    45334413  01/07/2020 12:00:00 AM  01/07/2020 12:00:01 AM  DOHMH   
6031    45334078  01/07/2020 12:00:00 AM  01/22/2020 12:00:01 AM  DOHMH   
6032    45333111  01/07/2020 12:00:00 AM  01/08/2020 12:00:01 AM  DOHMH   
6033    45329755  01/07/2020 12:00:00 AM  01/07/2020 04:37:08 PM  DOHMH   
6034    45332962  01/07/2020 12:00:00 AM  01/07/2020 01:41:32 PM  DOHMH   
6035    45333565  01/07/2020 12:00:00 AM  01/07/2020 01:42:09 PM  DOHMH   
6036    45334655  01/07/2020 12:00:00 AM  01/07/2020 04:36:42 PM  DOHMH   

                                  Agency Name  Complaint Type Descriptor  \
6029  Department of Health and Mental Hygiene  Food Poisoning  3 or More   
6030  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6031  Department of Health and Mental Hygiene  Food Poisoning  3 or More   
6032  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6033  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6034  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6035  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6036  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   

                   Location Type  Incident Zip         Incident Address  ...  \
6029       Other (Explain Below)       11206.0             LEWIS AVENUE  ...   
6030  Restaurant/Bar/Deli/Bakery       10018.0      49 WEST   39 STREET  ...   
6031                Retail Store       11206.0       1102 MYRTLE AVENUE  ...   
6032                  Restaurant       10001.0      11 WEST   32 STREET  ...   
6033                 Street Area       11004.0               255 STREET  ...   
6034                  Restaurant       11215.0             318 5 AVENUE  ...   
6035  Restaurant/Bar/Deli/Bakery       10013.0         80 BAYARD STREET  ...   
6036       Other (Explain Below)       11354.0  136-20 ROOSEVELT AVENUE  ...   

     Vehicle Type Taxi Company Borough Taxi Pick Up Location  \
6029          NaN                  NaN                   NaN   
6030          NaN                  NaN                   NaN   
6031          NaN                  NaN                   NaN   
6032          NaN                  NaN                   NaN   
6033          NaN                  NaN                   NaN   
6034          NaN                  NaN                   NaN   
6035          NaN                  NaN                   NaN   
6036          NaN                  NaN                   NaN   

     Bridge Highway Name Bridge Highway Direction Road Ramp  \
6029                 NaN                      NaN       NaN   
6030                 NaN                      NaN       NaN   
6031                 NaN                      NaN       NaN   
6032                 NaN                      NaN       NaN   
6033                 NaN                      NaN       NaN   
6034                 NaN                      NaN       NaN   
6035                 NaN                      NaN       NaN   
6036                 NaN                      NaN       NaN   

     Bridge Highway Segment   Latitude  Longitude  \
6029                    NaN  40.696689 -73.937792   
6030                    NaN  40.752255 -73.983852   
6031                    NaN  40.696817 -73.936605   
6032                    NaN  40.747414 -73.986091   
6033                    NaN  40.736363 -73.712831   
6034                    NaN  40.673030 -73.983100   
6035                    NaN  40.715732 -73.998755   
6036                    NaN  40.759785 -73.829236   

                                      Location  
6029   (40.69668857681533, -73.93779178748973)  
6030  (40.752255401079175, -73.98385207652169)  
6031  (40.696816933440644, -73.93660520135623)  
6032   (40.74741395808759, -73.98609084169061)  
6033   (40.73636320048617, -73.71283058158437)  
6034   

## 2. Print column list

In [62]:
df.columns.tolist()

['Unique Key',
 'Created Date',
 'Closed Date',
 'Agency',
 'Agency Name',
 'Complaint Type',
 'Descriptor',
 'Location Type',
 'Incident Zip',
 'Incident Address',
 'Street Name',
 'Cross Street 1',
 'Cross Street 2',
 'Intersection Street 1',
 'Intersection Street 2',
 'Address Type',
 'City',
 'Landmark',
 'Facility Type',
 'Status',
 'Due Date',
 'Resolution Description',
 'Resolution Action Updated Date',
 'Community Board',
 'BBL',
 'Borough',
 'X Coordinate (State Plane)',
 'Y Coordinate (State Plane)',
 'Open Data Channel Type',
 'Park Facility Name',
 'Park Borough',
 'Vehicle Type',
 'Taxi Company Borough',
 'Taxi Pick Up Location',
 'Bridge Highway Name',
 'Bridge Highway Direction',
 'Road Ramp',
 'Bridge Highway Segment',
 'Latitude',
 'Longitude',
 'Location']

## 3. Print total number of rows (length of data)

In [69]:
print(len(df))

6037


## 4. Print data header with certain columns 

In [72]:
print(df[['Agency Name','Complaint Type','City']].head(10))

                               Agency Name           Complaint Type  \
0  Department of Health and Mental Hygiene           Food Poisoning   
1  Department of Health and Mental Hygiene           Food Poisoning   
2  Department of Health and Mental Hygiene           Food Poisoning   
3  Department of Health and Mental Hygiene           Food Poisoning   
4  Department of Health and Mental Hygiene           Food Poisoning   
5  Department of Health and Mental Hygiene           Food Poisoning   
6  Department of Health and Mental Hygiene           Food Poisoning   
7          New York City Police Department      Noise - Residential   
8          New York City Police Department  Noise - Street/Sidewalk   
9          New York City Police Department      Noise - Residential   

           City  
0         BRONX  
1  Forest Hills  
2      NEW YORK  
3      NEW YORK  
4         BRONX  
5      NEW YORK  
6    Ozone Park  
7      BROOKLYN  
8         BRONX  
9      BROOKLYN  


## 5. Print data by index
Let's keep 6 columns used above ('Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', and 'Created Date')

## 6. Downsize data with certain columns

## 7. Rename columns 
Let's rename column 'Incident Zip' to 'Zipcode'

## 8. Check datatype

## 9. Convert data type
* Zipcode: float to object (string)

## Exercise: convert 'Created Date' column data type to datetime 
* Google it!
* Hint: pd.to_datetime


## 10. Print unique values of the column

## 11. Print rows based on values
* Print rows where "Zipcode" is 10011 and "Complaint Type" is 'Illegal Parking'

### Exercise: how many 311 service requests were reported in zipcode 10027 (Columbia Univ. neighborhood)?

## 12. Groupby

    Syntax:
    YOUR_DATAFRAME.groupby('COLUME_NAME').OPERATOR() 
    OPERATOR can be count, sum, min, max, mean, and so on.

* Let's groupby Borough to calculate how many 311 complaints were reported

### Exercise: how many complaints are averagely reported at the zipcode level?

## 13. Create a new column
* Create a column 'City' with value 'NYC' 

## 14. Export your dataframe as csv format
* After data cleaning, processing, or any other manipulation, you will need to export your dataframe as a new dataset. 
* This can be saved in 'output' folder.

        Syntax:
        YOUR_DATAFRAME.to_csv('FILE_PATH')
       