PLA6619 Introduction to Urban Data and Informatics I \
Tuesday, September 22, 2020 \
Week03

In [ ]:
# Comments in Python begin with a hash mark ( # ) 
# and whitespace character and continue to the end of the line. 
# Because comments do not execute, when you run a program 
# you will not see any indication of the comment there. 
# Comments are in the source code for humans to read, not for computers to execute.

In [1]:
# There are sometimes useless system warnings (which is not an error). 
# I put this codes to ignore errors
import warnings
warnings.filterwarnings("ignore")

# Lab 02
Please submit __Lab02.ipynb__ with outputs on Canvas after this lab session. It doesn't need to be perfect, but your submission will be reflected in attendance and participation. The solution of this notebook will be shared by end of today.
# PART 1: Intro to Python (continued)

## 1. Range

        range()
       
This range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.

        syntax:
        range(START_NUMBER, STOP_NUMBER, STEP_NUMBER)
        

In [2]:
x = list(range(5))
print (x)

[0, 1, 2, 3, 4]


In [3]:
# Create a sequence of numbers from 3 to 5, and print each item in the sequence:
x = list(range(3,6))
print (x)

[3, 4, 5]


In [4]:
# Create a sequence of numbers from 3 to 19, but increment by 2 instead of 1:
x = list(range(3, 20, 2))
print (x)

[3, 5, 7, 9, 11, 13, 15, 17, 19]


## 2. Calling Functions
    min()
    max()
    sum()
    len()

In [5]:
x = list(range(15))
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [6]:
print (min(x))
print (max(x))
print (sum(x))
print (len(x))

0
14
105
15


### Exercise: create a list with a sequence of number from 3 to 31, increment by 4, using range() and print mean value of the items.
* Create a list and assign variable.
* Assign variables using calling functions based on needs (e.g. min, max, sum, or len)
* Print mean value of the items in the list using mathematical expression.

In [7]:
myList = range(3, 32, 4)
a = sum(myList)
b = len(myList)

print (a/b)

17.0


## 3. Wrting Functions
A function is a block of code with only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result. The advantage of writing functions is you can easily use funciton for repeated processes with the same parameter structure. (e.g. calculator)

    Syntax:
    
    def YOUR_FUNCTION_NAME(PARAMETERS):
        WRITE_YOUR_CODE_HERE

In [8]:
# Writing a function
def myFunction(): # without a parameter
    print ("We are learning Python.")

In [9]:
# Use or call a function
myFunction()

We are learning Python.


In [10]:
# Writing a function
def myFunction(x,y):
    return x*y

In [11]:
myFunction(3,5)

15

In [12]:
myFunction(10,6)

60

In [13]:
# Writing a function (four fundamental arithmetic calculation)
def myFunction(x,y):
    a = x+y
    b = x-y
    c = x*y
    d = x/y
    return [a,b,c,d]

myFunction(9,5)

[14, 4, 45, 1.8]

### Exercise: write a function to return average value of items in a list.

In [14]:
def myFunction(inputList):
    print (sum(inputList)/len(inputList))
    
myFunction([1,4,5,8,2])

4.0


## 4. Control Statement (If-else)
* if
* elif
* else

In [15]:
a = 5
b = 30

if b > a:
    print ("b is greater than a.")

b is greater than a.


In [16]:
# The elif keyword is pythons way of saying "if the previous conditions were not true, then try this condition"

a = 33
b = 33
if b > a:
    print ("b is greater than a.")
elif a == b:
    print ("a and b are equal.")

a and b are equal.


In [17]:
# The else keyword catches anything which isn't caught by the preceding conditions
a = 200
b = 33
if b > a:
    print ("b is greater than a.")
elif a == b:
    print ("a and b are equal.")
else:
    print ("a is greater than b.")

a is greater than b.


## 5. For loops
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string). This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-oriented programming languages. With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.

    Syntax:
    for item in YOUR_SEQUENCE:
        do this
        do that
        ...

In [18]:
for i in range(6):
    print (i)

0
1
2
3
4
5


In [19]:
for city in ['New York', 'Boston', 'Chicago']:
    print ("I've traveled %s." %city)

I've traveled New York.
I've traveled Boston.
I've traveled Chicago.


In [20]:
# Print all combinations of lists
colors = ['red', 'yellow', 'blue']
items = ['pen', 'shirt', 'paper']

for c in colors: 
    for i in items:
        print (c, i)

red pen
red shirt
red paper
yellow pen
yellow shirt
yellow paper
blue pen
blue shirt
blue paper


In [21]:
# For loop with controlling statement
for i in range(5): 
    if i == 3:
        print ('Three')
    else:
        print (i)

0
1
2
Three
4


In [22]:
# You can pass
for i in range(5):
    if i == 3:
        pass
    else:
        print (i)

0
1
2
4


In [23]:
# You can break a script
for i in range(5):
    if i == 3:
        break
    else:
        print (i)

0
1
2


### Exercise: create a function to get all availabe combinations based on the following statements.
* Create two lists [1, 3, 5, 7] and [2, 4, 6, 8] using a range() function.
* Print out all available combinations of two items from each list if a multiplication result is not 12. For example, 3 and 4 shouldn't be printed out.
* Break a script once a for loop once a for loop takes 7 from the first list.
Ideal output would be 
        1 2
        1 4
        1 6
        1 8
        3 2
        3 6
        3 8
        5 2
        5 4
        5 6
        5 8

In [24]:
myList1 = list(range(1,8,2))
myList2 = list(range(2,9,2))

for i in myList1:
    for j in myList2:
        x = i*j
        if x == 12:
            pass
        elif i == 7:
            break
        else:
            print (i, j)

1 2
1 4
1 6
1 8
3 2
3 6
3 8
5 2
5 4
5 6
5 8


# PART 2: Essential Libraries - Numpy
NumPy is one of the fundamental packages for scientific computing in the browser.

* Multimensional arrays
* High-level mathematical functions such as linear algebra operations
* Important, because the NumPy array is the fundamental data structure in scikit-learn (which will be mainly used for machine learning algorithms)
* Data will have to be converted to a NumPy array
* Core functionality: ndarray class, multidimensinal (n-dimensional) array
* All elements in the array must be of the same data type (e.g. int, str, float...)


## Import Numpy module

In [25]:
import numpy as np

## 1. Create a numpy array

In [26]:
# Create 2 by 3 numpy array 
x = np.array([[1,2,3],
              [4,5,6]])

print (x)

[[1 2 3]
 [4 5 6]]


## 2. Shape of matrix (array)

In [27]:
print (x.shape)

(2, 3)


## 3. Indexing

In [28]:
# Array indexing
print (x[0])
print (x[1])
print (x[0][0])
print (x[1][2])

[1 2 3]
[4 5 6]
1
6


__Accessing array rows and columns__ \
One commonly needed routine is accessing single rows or columns of an array. You can do this by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [29]:
# First column
print (x[:, 0])

# Third column
print (x[:, 2])

[1 4]
[3 6]


## 4. Numpy's arithmetic operators

In [30]:
x = np.array([1,2,3,4,5,6])

print (x+3)
print (x-10)
print (x*3)

[4 5 6 7 8 9]
[-9 -8 -7 -6 -5 -4]
[ 3  6  9 12 15 18]


In [31]:
# Absolute, log, exp values
# The inverse of the exponentials, the logarithms, are also available. 
# The basic np.log gives the natural logarithm; if you prefer to compute the base-2 logarithm or 
# the base-10 logarithm, these are available as well:

## 5. Calling built-in functions

In [32]:
x = np.array([[1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])

print (x.sum())
print (x.min())
print (x.argmin()) # Find index of minimum value 
print (x.max())
print (x.argmax()) # Find index of maximum value
print (x.mean())
print (x.std())

60
1
0
7
14
4.0
1.632993161855452


In [33]:
# Or, NumPy functions can be used as other format like below
print (np.median(x))
print (np.sum(x))
print (np.min(x))
print (np.argmin(x))
print (np.argmax(x))
print (np.mean(x))
print (np.std(x))

4.0
60
1
0
14
4.0
1.632993161855452


# PART 3: Pandas
Pandas is a Python library for data wrangling and analysis.

* Data structure called the DataFrame - modeled after the R DataFrame
* Simply, it is like a table, similar to an Excel spreadsheet
* Great range of methods to modify and operate on data tables
* SQL-like queries, joins of tables
* In contrast to NumPy, Pandas allows each column to have a separate data type (e.g. one for string, one for float, one for datetime etc.)
* Ingest from a variety of data file formats and data bases (SQL, Excel file, csv, json)

### Import pandas module


In [34]:
import pandas as pd

## 1. Create a pandas dataframe

In [35]:
# Create a simple dataset using dictionary
data = {'Name': ["John", "Anna", "Peter", "Linda", "Nick"],
       'Location': ["New York", "Paris", "Berlin", "London", "Barcelona"],
       'Major': ["Architecture", "Urban Planning", "Urban Design", "Computer Science", "Fine Arts"],
       'Age': [28, 30, 27, 25, 26]}

print (data)

{'Name': ['John', 'Anna', 'Peter', 'Linda', 'Nick'], 'Location': ['New York', 'Paris', 'Berlin', 'London', 'Barcelona'], 'Major': ['Architecture', 'Urban Planning', 'Urban Design', 'Computer Science', 'Fine Arts'], 'Age': [28, 30, 27, 25, 26]}


In [36]:
# Convert this dictionary to pandas dataframe
data_pandas = pd.DataFrame(data)

In [37]:
# Pandas dataframe allows pretty printing of dataframes
data_pandas

Name   Location             Major  Age
0   John   New York      Architecture   28
1   Anna      Paris    Urban Planning   30
2  Peter     Berlin      Urban Design   27
3  Linda     London  Computer Science   25
4   Nick  Barcelona         Fine Arts   26

## 2. Data shape, columns, and rows

In [38]:
print ("Shape of data_pandas: ",data_pandas.shape)

Shape of data_pandas:  (5, 4)


In [39]:
# Print all columns
print ("Column names: ",data_pandas.columns.tolist())

Column names:  ['Name', 'Location', 'Major', 'Age']


In [40]:
# Call data associated a columne
data_pandas['Name']

0     John
1     Anna
2    Peter
3    Linda
4     Nick
Name: Name, dtype: object

In [41]:
data_pandas.Name

0     John
1     Anna
2    Peter
3    Linda
4     Nick
Name: Name, dtype: object

In [42]:
data_pandas[['Name', 'Major']] # multiple columns

Name             Major
0   John      Architecture
1   Anna    Urban Planning
2  Peter      Urban Design
3  Linda  Computer Science
4   Nick         Fine Arts

## 3. Data types

In [43]:
data_pandas.dtypes

Name        object
Location    object
Major       object
Age          int64
dtype: object

## 4. Data indexing and selection

In [44]:
# Show the rows based on index
data_pandas.iloc[1:3] # rows with index 1 through 3 (stop before index 3)

Name Location           Major  Age
1   Anna    Paris  Urban Planning   30
2  Peter   Berlin    Urban Design   27

In [45]:
# Show the rows based on the value
# Syntax: DataFrameName[ConditionStatement]
data_pandas[data_pandas['Age']>27]

Name  Location           Major  Age
0  John  New York    Architecture   28
1  Anna     Paris  Urban Planning   30

In [46]:
data_pandas[data_pandas['Major']=='Urban Planning']

Name Location           Major  Age
1  Anna    Paris  Urban Planning   30

## 5. Sorting
Even though the dataframe is sorted, the original index will be kept. If you want to change or reset the index, you can use 'DataFrame.reset_index()' command.
    
    syntax
    YOUR_DATAFRAME.sort_values(by='COLUMN_NAME', ascending='False')   ascending='True' is default

In [47]:
data_pandas.sort_values(by='Age') # Try ascending='False'

Name   Location             Major  Age
3  Linda     London  Computer Science   25
4   Nick  Barcelona         Fine Arts   26
2  Peter     Berlin      Urban Design   27
0   John   New York      Architecture   28
1   Anna      Paris    Urban Planning   30

## 6. Basic functions

In [48]:
print (data_pandas['Age'].min()) # Minimum value
print (data_pandas['Age'].max()) # Maximum value
print (data_pandas['Age'].mean()) # Mean value
print (data_pandas['Age'].std()) # Standard deviation
print (data_pandas['Age'].median()) # Median value

25
30
27.2
1.9235384061671346
27.0


# PART 4: Play with data (TIPS FOR THE ASSIGNMENT!)
By using Pandas, various file formats can be loaded for data analysis.
* Excel
* CSV
* JSON
* APIs

## 1. Load NYC311 data (311 service requests data subset) 

In [49]:
df = pd.read_csv('../data/311_Service_Requests_01062020.csv')

In [50]:
df.head()

Unique Key            Created Date             Closed Date Agency  \
0    45321376  01/06/2020 12:00:00 AM  01/22/2020 12:00:01 AM  DOHMH   
1    45322953  01/06/2020 12:00:00 AM  01/21/2020 12:00:01 AM  DOHMH   
2    45319607  01/06/2020 12:00:00 AM  01/06/2020 12:00:01 AM  DOHMH   
3    45319110  01/06/2020 12:00:00 AM  01/21/2020 12:00:01 AM  DOHMH   
4    45319119  01/06/2020 12:00:00 AM  01/07/2020 01:35:26 PM  DOHMH   

                               Agency Name  Complaint Type Descriptor  \
0  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
1  Department of Health and Mental Hygiene  Food Poisoning  3 or More   
2  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
3  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
4  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   

                Location Type  Incident Zip                  Incident Address  \
0         1-2 Family Dwelling       10467.0            3311 WHITE PLAINS ROAD   
1  Restaurant/Bar/Deli/Bakery       11375.0                  64-18 108 STREET   
2  Restaurant/Bar/Deli/Bakery       10128.0                     1664 3 AVENUE   
3                  Restaurant       10039.0  2730 FREDRICK DOUGLASS BOULEVARD   
4         1-2 Family Dwelling       10467.0            3311 WHITE PLAINS ROAD   

   ... Vehicle Type Taxi Company Borough Taxi Pick Up Location  \
0  ...          NaN                  NaN                   NaN   
1  ...          NaN                  NaN                   NaN   
2  ...          NaN                  NaN                   NaN   
3  ...          NaN                  NaN                   NaN   
4  ...          NaN                  NaN                   NaN   

  Bridge Highway Name Bridge Highway Direction Road Ramp  \
0                 NaN                      NaN       NaN   
1                 NaN                      NaN       NaN   
2                 NaN                      NaN       NaN   
3                 NaN                      NaN       NaN   
4                 NaN                      NaN       NaN   

  Bridge Highway Segment   Latitude  Longitude  \
0                    NaN  40.873639 -73.867095   
1                    NaN  40.732517 -73.849397   
2                    NaN  40.783423 -73.950634   
3                    NaN  40.822932 -73.941832   
4                    NaN  40.873639 -73.867095   

                                   Location  
0    (40.8736393816693, -73.86709503705343)  
1   (40.73251661488513, -73.84939676972941)  
2  (40.783423466965544, -73.95063441884525)  
3   (40.82293243748226, -73.94183246541331)  
4    (40.8736393816693, -73.86709503705343)  

[5 rows x 41 columns]

In [51]:
df.tail()

Unique Key            Created Date             Closed Date Agency  \
6032    45333111  01/07/2020 12:00:00 AM  01/08/2020 12:00:01 AM  DOHMH   
6033    45329755  01/07/2020 12:00:00 AM  01/07/2020 04:37:08 PM  DOHMH   
6034    45332962  01/07/2020 12:00:00 AM  01/07/2020 01:41:32 PM  DOHMH   
6035    45333565  01/07/2020 12:00:00 AM  01/07/2020 01:42:09 PM  DOHMH   
6036    45334655  01/07/2020 12:00:00 AM  01/07/2020 04:36:42 PM  DOHMH   

                                  Agency Name  Complaint Type Descriptor  \
6032  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6033  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6034  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6035  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
6036  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   

                   Location Type  Incident Zip         Incident Address  ...  \
6032                  Restaurant       10001.0      11 WEST   32 STREET  ...   
6033                 Street Area       11004.0               255 STREET  ...   
6034                  Restaurant       11215.0             318 5 AVENUE  ...   
6035  Restaurant/Bar/Deli/Bakery       10013.0         80 BAYARD STREET  ...   
6036       Other (Explain Below)       11354.0  136-20 ROOSEVELT AVENUE  ...   

     Vehicle Type Taxi Company Borough Taxi Pick Up Location  \
6032          NaN                  NaN                   NaN   
6033          NaN                  NaN                   NaN   
6034          NaN                  NaN                   NaN   
6035          NaN                  NaN                   NaN   
6036          NaN                  NaN                   NaN   

     Bridge Highway Name Bridge Highway Direction Road Ramp  \
6032                 NaN                      NaN       NaN   
6033                 NaN                      NaN       NaN   
6034                 NaN                      NaN       NaN   
6035                 NaN                      NaN       NaN   
6036                 NaN                      NaN       NaN   

     Bridge Highway Segment   Latitude  Longitude  \
6032                    NaN  40.747414 -73.986091   
6033                    NaN  40.736363 -73.712831   
6034                    NaN  40.673030 -73.983100   
6035                    NaN  40.715732 -73.998755   
6036                    NaN  40.759785 -73.829236   

                                     Location  
6032  (40.74741395808759, -73.98609084169061)  
6033  (40.73636320048617, -73.71283058158437)  
6034   (40.67303049309962, -73.9830997896011)  
6035  (40.71573208700158, -73.99875548037697)  
6036  (40.75978506574562, -73.82923633167887)  

[5 rows x 41 columns]

## 2. Print column list

In [52]:
print (df.columns.tolist())

['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name', 'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip', 'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2', 'Intersection Street 1', 'Intersection Street 2', 'Address Type', 'City', 'Landmark', 'Facility Type', 'Status', 'Due Date', 'Resolution Description', 'Resolution Action Updated Date', 'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)', 'Y Coordinate (State Plane)', 'Open Data Channel Type', 'Park Facility Name', 'Park Borough', 'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment', 'Latitude', 'Longitude', 'Location']


## 3. Print total number of rows (length of data)

In [53]:
print (len(df))

6037


## 4. Print data header with certain columns 

In [54]:
df[['Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', 'Created Date']].head()

Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   
2    45319607  Department of Health and Mental Hygiene  Food Poisoning   
3    45319110  Department of Health and Mental Hygiene  Food Poisoning   
4    45319119  Department of Health and Mental Hygiene  Food Poisoning   

   Incident Zip    Borough            Created Date  
0       10467.0      BRONX  01/06/2020 12:00:00 AM  
1       11375.0     QUEENS  01/06/2020 12:00:00 AM  
2       10128.0  MANHATTAN  01/06/2020 12:00:00 AM  
3       10039.0  MANHATTAN  01/06/2020 12:00:00 AM  
4       10467.0      BRONX  01/06/2020 12:00:00 AM

## 5. Print data by index
Let's keep 6 columns used above ('Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', and 'Created Date')

In [55]:
df[['Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', 'Created Date']].iloc[300:305]

Unique Key                                        Agency Name  \
300    45325465                    New York City Police Department   
301    45326017             Department of Environmental Protection   
302    45321176  Department of Housing Preservation and Develop...   
303    45320852                    New York City Police Department   
304    45319309                    New York City Police Department   

          Complaint Type  Incident Zip        Borough            Created Date  
300      Illegal Parking       11216.0       BROOKLYN  01/06/2020 03:03:50 AM  
301                Noise       11206.0       BROOKLYN  01/06/2020 03:07:00 AM  
302       HEAT/HOT WATER       10302.0  STATEN ISLAND  01/06/2020 03:08:54 AM  
303   Noise - Commercial       10468.0          BRONX  01/06/2020 03:09:15 AM  
304  Noise - Residential       11354.0         QUEENS  01/06/2020 03:09:50 AM

## 6. Downsize data with certain columns

In [56]:
df2 = df[['Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', 'Created Date']]
df2.head(2)

Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   

   Incident Zip Borough            Created Date  
0       10467.0   BRONX  01/06/2020 12:00:00 AM  
1       11375.0  QUEENS  01/06/2020 12:00:00 AM

## 7. Rename columns 
Let's rename column 'Incident Zip' to 'Zipcode'

In [57]:
df2.rename(columns = {'Incident Zip':'Zipcode'}, inplace = True) 
df2.head(2)

Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   

   Zipcode Borough            Created Date  
0  10467.0   BRONX  01/06/2020 12:00:00 AM  
1  11375.0  QUEENS  01/06/2020 12:00:00 AM

## 8. Check datatype

In [58]:
print (df2.dtypes)

Unique Key          int64
Agency Name        object
Complaint Type     object
Zipcode           float64
Borough            object
Created Date       object
dtype: object


## 9. Convert data type
* Zipcode: float to object (string)

In [59]:
df2['Zipcode'] = df2['Zipcode'].astype(str).str[0:5]
df2.head(2)

Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   

  Zipcode Borough            Created Date  
0   10467   BRONX  01/06/2020 12:00:00 AM  
1   11375  QUEENS  01/06/2020 12:00:00 AM

In [60]:
print (df2.dtypes)

Unique Key         int64
Agency Name       object
Complaint Type    object
Zipcode           object
Borough           object
Created Date      object
dtype: object


## Exercise: convert 'Created Date' column data type to datetime 
* Google it!
* Hint: pd.to_datetime


## 10. Print unique values of the column

In [61]:
print (df2['Agency Name'].unique())

['Department of Health and Mental Hygiene'
 'New York City Police Department' 'Department of Buildings'
 'Department of Transportation' 'Department of Environmental Protection'
 'Department of Housing Preservation and Development'
 'Taxi and Limousine Commission' 'BCC - Queens West'
 'Department of Sanitation' 'BCC - Brooklyn South'
 'Department of Parks and Recreation' 'Department of Consumer Affairs'
 'A - Staten Island' 'Brooklyn North 03' 'Bronx 11' 'Queens West 04'
 'A - Brooklyn' 'BCC - Bronx' 'BCC - Brooklyn North'
 'Economic Development Corporation' 'BCC - Queens East' 'A - Queens'
 'A - Manhattan' 'Department of Homeless Services' 'Bronx 05'
 'Manhattan 04' 'Queens East 12' 'Manhattan 01' 'BCC - Staten Island'
 'Manhattan 02' 'Queens West 03' 'Department of Education' 'Manhattan 03'
 'Bronx 08' 'Bronx 03' 'A - Canine Task Force Citywide' 'Manhattan 07'
 'Manhattan 05' 'Manhattan 08' 'A - Bronx' 'Brooklyn South 10'
 'A - Illegal Posting Staten Island, Queens and Brooklyn' 'Bron

In [62]:
# Print unique values of the column with counts
print (df2['Agency Name'].value_counts())

New York City Police Department                           1928
Department of Housing Preservation and Development        1315
Department of Transportation                               934
Department of Environmental Protection                     390
Department of Buildings                                    388
Department of Sanitation                                   308
Department of Health and Mental Hygiene                    185
Department of Parks and Recreation                         130
Taxi and Limousine Commission                               93
Department of Homeless Services                             43
BCC - Brooklyn South                                        40
Department of Consumer Affairs                              34
BCC - Brooklyn North                                        31
BCC - Queens West                                           26
A - Brooklyn                                                22
BCC - Staten Island                                    

## 11. Print rows based on values
* Print rows where "Zipcode" is 10011 and "Complaint Type" is 'Illegal Parking'

In [65]:
df2[(df2['Zipcode']=='10011') & (df2['Complaint Type']=='Illegal Parking')]

Unique Key                      Agency Name   Complaint Type Zipcode  \
4993    45325003  New York City Police Department  Illegal Parking   10011   
5959    45322573  New York City Police Department  Illegal Parking   10011   
5975    45320348  New York City Police Department  Illegal Parking   10011   

        Borough            Created Date  
4993  MANHATTAN  01/06/2020 07:48:07 PM  
5959  MANHATTAN  01/06/2020 11:41:21 PM  
5975  MANHATTAN  01/06/2020 11:44:16 PM

### Exercise: how many 311 service requests were reported in zipcode 10027 (Columbia Univ. neighborhood)?

## 12. Groupby

    Syntax:
    YOUR_DATAFRAME.groupby('COLUME_NAME').OPERATOR() 
    OPERATOR can be count, sum, min, max, mean, and so on.
* A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.
* Let's groupby Borough to calculate how many 311 complaints were reported

In [66]:
df2.groupby('Borough').count()

Unique Key  Agency Name  Complaint Type  Zipcode  Created Date
Borough                                                                      
BRONX                1069         1069            1069     1069          1069
BROOKLYN             1763         1763            1763     1763          1763
MANHATTAN            1417         1417            1417     1417          1417
QUEENS               1485         1485            1485     1485          1485
STATEN ISLAND         261          261             261      261           261
Unspecified            42           42              42       42            42

### Exercise: how many complaints are averagely reported at the zipcode level?

## 13. Create a new column
* Create a column 'City' with value 'NYC' 

In [68]:
df2['City'] = 'NYC'
df2.head(2)

Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   

  Zipcode Borough            Created Date City  
0   10467   BRONX  01/06/2020 12:00:00 AM  NYC  
1   11375  QUEENS  01/06/2020 12:00:00 AM  NYC

## 14. Export your dataframe as csv format
* After data cleaning, processing, or any other manipulation, you will need to export your dataframe as a new dataset. 
* This can be saved in 'output' folder.

        Syntax:
        YOUR_DATAFRAME.to_csv('FILE_PATH')
       

In [69]:
df2.to_csv('../output/Lab02_NYC311_test_output.csv')